### ISSUE TITLE
Why you are using conv2d in the Discriminator?

### ISSUE THREAD

**Issue by hbk16** [ginobilinie/medSynthesisV1#1]
These codes are full of bugs, e.g., Discriminator is implementing conv2d, and the UNetUpBlock.center_crop misses the last dimension of a tensor. Hope they will be fixed in a future version.

**Comment by ginobilinie** [comment]
@hbk16 
Thanks for correction.

Since this is an extension version which tries Unet as generator and wgan-gp as Discriminator. Currently, the code is mainly working on 2D, and the codes in Unet2d_pytorch.py are fine (we are currently mainly testing on the 2D).

We will update the 3D version as soon as we can. Sorry for the confusion. And we have a 3d version with tensorflow.

**Comment by ginobilinie** [comment]
@hbk16 
Here is the original 3d version in TF (since we create it as early as 2016, part of the codes may be deprecated. And that's also partially the reason we implement a new one with pytorch) 

https://github.com/ginobilinie/medSynthesis/tree/master/3dversion

**Comment by hbk16** [comment]
Thank you.
BTW, the Generator in this code is a bit different from the one described in your paper.

**Comment by hbk16** [comment]
Thank you.
BTW, since the input size of the generator is 32x32x32 and the output size is 16x16x16, it seems that there should be a down sampling layer before the input being add to the residual output, which is not described in the paper.

**Comment by ginobilinie** [comment]
@hbk16 
We do not involve a down sampling layer in the FCN since downsampling layer will lose too much information and it is bad for image synthesis. We only involve convs+(bn+)relu in the FCN. 
As in the code we uploaded, it is source image: 32x32x32-> target image: 24x24x24. If you need that 32x32x32->16x16x16, I can also find it and share with you.

**Comment by hbk16** [comment]
Many thanks.
It would be really appreciated if you can send the model to 951522809@qq.com or make a new commit.

**Comment by ginobilinie** [comment]
Sure
