### ISSUE TITLE
[Question] How many images can we synthesize, relative to the number of training images?

### ISSUE THREAD

**Issue by cardyfib** [ginobilinie/medSynthesisV1#4]
Hi @ginobilinie ,
Thank you for this repository! I am experimenting with medical image synthesis and I have a general question on synthesizing images using GANs. I would appreciate any inputs on it.

I am assuming there should be some limit on the number of different images we can generate using a trained generator. Is that number a ratio of the number of trainset images? For example, if we train the GAN with 1000 MRIs, can we synthesize 2000 (twice as much) new MRIs? 

Is there a procedure (or a hack) to estimate the number of images that can be synthesized?

Thanks in advance!

**Comment by ginobilinie** [comment]
@cardyfib 
Thanks for your interest. In our case, we use a supervised generator (generator has L1/L2 loss to guide itself except the adversarial loss), so we are actually not the standard (classical) GAN. Given an input MRI, we can generate a corresponding CT (of course, we need the input MRI not quite varies largely from the training set). Thus, we argue there is no such limit of numbers for generated MRIs.

BTW, for standard (classical) GAN, there is also no limit of numbers for generated images. Since the generator in the standard GAN can learn the distribution of the input training images, so it can generate numerous images following the distribution (just like bootstrap).

**Comment by cardyfib** [comment]
Thanks for your response!
